// Complete Pakistan administrative location dataset for cascading dropdowns.
// Structure: Province -> District -> Tehsil[]
// Covers all 4 provinces (Punjab, Sindh, Khyber Pakhtunkhwa, Balochistan),
// Islamabad Capital Territory, Gilgit-Baltistan, and Azad Jammu & Kashmir —
// 154 districts and 600+ tehsils in total.
export type PakistanLocationData = Record<string, Record<string, string[]>>

export const PAKISTAN_LOCATIONS: PakistanLocationData = {
  'Azad Jammu and Kashmir': {
    'Bagh': ['Bagh', 'Dhirkot', 'Hari Ghel', 'Rera'],
    'Bhimber': ['Barnala', 'Bhimber', 'Samahni'],
    'Hattian Bala': ['Chikkar', 'Hattian Bala', 'Leepa'],
    'Haveli': ['Birpani', 'Haveli', 'Khurshidabad', 'Mumtazabad'],
    'Kotli': ['Charhoi', 'Dulyan Jattan', 'Fatehpur Thakiala', 'Khuiratta', 'Kotli', 'Sehnsa'],
    'Mirpur': ['Dadyal', 'Mirpur'],
    'Muzaffarabad': ['Muzaffarabad', 'Nasirabad'],
    'Neelum': ['Athmuqam', 'Sharda'],
    'Poonch': ['Abbaspur', 'Hajira', 'Rawalakot', 'Thorar'],
    'Sudhnati': ['Balouch', 'Mang', 'Pallandri'],
  },
  'Balochistan': {
    'Awaran': ['Awaran', 'Gishkore Sub', 'Jhal Jao Sub-Tehsil', 'Mashkai'],
    'Barkhan': ['Barkhan'],
    'Chagai': ['Chagai Sub-Tehsil', 'Dalbandin', 'Nokundi Sub-Tehsil', 'Taftan Sub-Tehsil'],
    'Dera Bugti': ['Baiker Sub-Tehsil', 'Dera Bugti', 'Loti', 'Malam Sub-Tehsil', 'Phelawagh ', 'Pir Koh Sub-Tehsil', 'Sangsillah Sub-Tehsil', 'Sui'],
    'Gwadar': ['Gwadar ', 'Jiwani', 'Ormara ', 'Pasni', 'Suntsar Sub-Tehsil '],
    'Harnai': ['Harnai', 'Khoast Sub-Tehsil', 'Shahrig'],
    'Jaffarabad': ['Gandhaka ', 'Jhat Pat', 'Usta Muhammad'],
    'Jhal Magsi': ['Gandawa', 'Jhal Magsi', 'Mirpur Sub-Tehsil'],
    'Kachhi (Bolan)': ['Balanari Sub-Tehsil', 'Dhadar', 'Khattan Sub-Tehsil', 'Mach', 'Sanni Sub-Tehsil'],
    'Kalat': ['Gazg Sub-Tehsil', 'Johan Sub-Tehsil', 'Kalat', 'Mangochar Sub-Tehsil', 'Surab Sub-Tehsil'],
    'Kech': ['Balnigor Sub-Tehsil', 'Buleda Sub-Tehsil', 'Dasht Sub-Tehsil ', 'Hoshab Sub-Tehsil', 'Kech (Turbat) ', 'Mand Sub-Tehsil ', 'Tump', 'Zamuran Sub-Tehsil '],
    'Kharan': ['Kharan ', 'Sar Kharan ', 'TohMulk Sub '],
    'Khuzdar': ['Aranji Sub-Tehsil', 'Karakh Sub-Tehsil', 'Khuzdar', 'Moola Sub-Tehsil', 'Nal Sub-Tehsil', 'Ornach Sub-Tehsil', 'Saroona Sub-Tehsil ', 'Wadh Sub-Tehsil', 'Zehri'],
    'Killa Abdullah': ['Chaman', 'Dobandi Sub-Tehsil', 'Gulistan', 'Killa Abdullah'],
    'Killa Saifullah': ['Baddini Sub-Tehsil', 'Kan Mehtarzai Sub-Tehsil', 'Killa Saifullah', 'Loiband', 'Muslim Bagh', 'Shinki Sub-Tehsil'],
    'Kohlu': ['Grisani Sub-Tehsil ', 'Kahan', 'Kohlu', 'Mawand', 'Tamboo'],
    'Lasbela': ['Bela', 'Dureji ', 'Gadani', 'Hub', 'Kanraj', 'Lakhra ', 'Liari Sub-Tehsil', 'Sonmiani/Winder', 'Uthal'],
    'Lehri': ['Bhag', 'Lehri '],
    'Loralai': ['Bori', 'Duki', 'Loralai', 'Mekhtar Sub-Tehsil'],
    'Mastung': ['Dasht Sub-Tehsil', 'Khad Koocha Sub-Tehsil', 'Kirdgap Sub-Tehsil ', 'Mastung'],
    'Musakhel': ['Drug', 'Kingri', 'Musakhel'],
    'Nasirabad': ['Baba Kot', 'Chattar', 'D.M.Jamali', 'Tamboo'],
    'Nushki': ['Nushki'],
    'Panjgur': ['Gichk Sub-Tehsil', 'Gowargo', 'Panjgur', 'Parome'],
    'Pishin': ['Barshore Sub-Tehsil', 'Hurramzai Sub-Tehsil', 'Karezat Sub-Tehsil', 'Pishin', 'Saranan'],
    'Quetta': ['Panj Pai Sub', 'Quetta City', 'Quetta Sadar'],
    'Sheerani (Sherani)': ['Sherani Sub-Division'],
    'Sibi': ['Kotmandai Sub-Tehsil', 'Sangan Sub-Tehsil', 'Sibi'],
    'Sohbatpur': ['Faridabad', 'Sanhri', 'Sohbatpur'],
    'Washuk': ['Besima Sub-Tehsil', 'Musakhel Sub-Tehsil ', 'Nag Sub-Tehsil', 'Shahoo Garhi Sub-Tehsil', 'Washuk Sub-Tehsil'],
    'Zhob': ['Ashwat Sub-Tehsil', 'Kashatoo Sub-Tehsil ', 'Qamar Din Karez', 'Sambaza Sub-Tehsil', 'Zhob'],
    'Ziarat': ['Sinjawi Sub-Tehsil ', 'Ziarat'],
  },
  'Gilgit Baltistan': {
    'Astore': ['Astore', 'Shounter'],
    'Darel': ['Darel'],
    'Diamer': ['Babusar', 'Chilas', 'Goharabad'],
    'Ghanche': ['Chorbat', 'Daghoni', 'Haldi (Ghowari)', 'Keris', 'Khaplu', 'Mashabrum'],
    'Ghizer': ['Gahkuch', 'Ishkoman', 'Punial'],
    'Gilgit': ['Danyor', 'Gilgit', 'Jaglot'],
    'Gupis–Yasin': ['Gupis', 'Phander', 'Yasin'],
    'Hunza': ['Aliabad', 'Gojal', 'Shinaki'],
    'Kharmang': ['Kharmang'],
    'Nagar': ['Chalt', 'Nagar-I', 'Nagar-II (Sikandarabad)'],
    'Roundu': ['Roundu'],
    'Shigar': ['Gulabpur', 'Shigar'],
    'Skardu': ['Gamba', 'Gultari', 'Skardu'],
    'Tangir': ['Tangir'],
  },
  'Islamabad': {
    'Islamabad': ['Rural Islamabad', 'Zone I', 'Zone II', 'Zone III', 'Zone IV', 'Zone V'],
  },
  'Khyber Pakhtunkhwa': {
    'Abbottabad': ['Abbottabad', 'Havelian'],
    'Bajaur': ['Bar Chamer Kand', 'Barang', 'Khar Bajaur', 'Mamund', 'Nawagai', 'Salarzai', 'Utmankhel (Qzafi)'],
    'Bannu': ['Bannu', 'Domel'],
    'Batagram': ['Allai', 'Batagram '],
    'Buner': ['Daggar/Buner ', 'Gagra', 'Khado Khel', 'Mandanr'],
    'Charsadda': ['Charsadda', 'Shabqadar', 'Tangi'],
    'Chitral': ['Chitral', 'Mastuj'],
    'Dera Ismail Khan': ['Daraban', 'Dera Ismail Khan (D.I.Khan)', 'Kulachi', 'Pahar Pur', 'Paroa'],
    'Hangu': ['Hangu', 'Tall'],
    'Haripur': ['Ghazi', 'Haripur'],
    'Karak': ['Banda Daud Shah', 'Karak', 'Takht-e-Nasriti '],
    'Khyber': ['Bara', 'Jamrud', 'Landi Kotal', 'Mula Ghori'],
    'Kohat': ['Kohat ', 'Lachi'],
    'Kohistan (Lower Kohistan - Upper Kohistan)': ['Dassu', 'Kandia', 'Palas', 'Pattan'],
    'Kurram': ['Central Kurram Frontier Region', 'Lower Kurram', 'Upper Kurram'],
    'Lakki Marwat': ['Lakki Marwat', 'Naurang'],
    'Lower Dir': ['Adenzai', 'Lal Qilla', 'Samarbagh (Barwa)', 'Temergara'],
    'Malakand': ['Sam Ranizai', 'Swat Ranizai'],
    'Mansehra': ['Balakot', 'Mansehra', 'Oghi '],
    'Mardan': ['Katlang', 'Mardan', 'Takht Bhai'],
    'Mohmand': ['Halimzai', 'Pindiali', 'Pringhar', 'Safi', 'Upper Mohmand', 'Utman Khel (Ambar)', 'Yake Ghund'],
    'North Waziristan': ['Datta Khel', 'Dossali', 'Garyum', 'Ghulam Khan', 'Mir Ali', 'Miran Shah', 'Razmak', 'Shewa', 'Spinwam'],
    'Nowshera': ['Jehangira', 'Nowshera', 'Pabbi'],
    'Orakzai': ['Central', 'Ismailzai', 'Lower', 'Upper'],
    'Peshawar': ['Peshawar'],
    'Shangla': ['Alpuri', 'Besham', 'Puran'],
    'South Waziristan': ['Birmal', 'Ladha', 'Makin (Charlai)', 'Sararogha', 'Sarwekai', 'Tiarza', 'Toi Khullah', 'Wana'],
    'Swabi': ['Lahor', 'Rzzar', 'Swabi', 'Topi'],
    'Swat': ['Babuzai (Swat)', 'Bari Kot', 'Behrain', 'Charbagh', 'Kabal', 'Khawaza Khela', 'Matta'],
    'Tank': ['Tank'],
    'Tor Ghar (Kala Dhaka)': ['Judba', 'Khander'],
    'Upper Dir': ['Dir', 'Shringal', 'Wari'],
  },
  'Punjab': {
    'Attock': ['Attock ', 'Fateh Jang', 'Hassan Abdal', 'Hazro', 'Jand', 'Pindi Gheb'],
    'Bahawalnagar': ['Bahawalnagar ', 'Chishtian', 'Fort Abbas', 'Haroonabad ', 'Minchinabad'],
    'Bahawalpur': ['Ahmadpur East', 'Bahawalpur City', 'Bahawalpur Saddar', 'Hasilpur', 'Khairpur Tamewali', 'Yazman'],
    'Bhakkar': ['Bhakkar', 'Darya Khan', 'Kalur Kot', 'Mankera '],
    'Chakwal': ['Chakwal', 'Choa Saidan Shah', 'Kallar Kahar', 'Lawa', 'Talagang'],
    'Chiniot': ['Bhawana', 'Chiniot', 'Lalian'],
    'Dera Ghazi Khan': ['De-excluded area of D.G.Khan', 'Dera Ghazi Khan', 'Kot Chutta', 'Taunsa '],
    'Faisalabad': ['Chak Jhumra', 'Faisalabad City', 'Faisalabad Saddar', 'Jaranwala', 'Sammundri', 'Tandlianwala'],
    'Gujranwala': ['Gujranwal Saddar', 'Gujranwala City', 'Kamoki', 'Nowshera Virkan', 'Wazirabad '],
    'Gujrat': ['Gujrat', 'Kharian ', 'Sarai Alamgir'],
    'Hafizabad': ['Hafizabad', 'Pindi Bhattian'],
    'Jhang': ['18 Hazari', 'Ahmadpur Sial ', 'Jhang ', 'Shorkot'],
    'Jhelum': ['Dina', 'Jhelum', 'Pind Dadan Khan', 'Sohawa'],
    'Kasur': ['Chunian', 'Kasur', 'Kot Radha Kishan', 'Pattoki '],
    'Khanewal': ['Jehanian', 'Kabirwala', 'Khanewal', 'Mian Channu'],
    'Khushab': ['Khushab', 'Nowshera', 'Nurpur', 'Quaidabad '],
    'Lahore': ['Lahore Cantt.', 'Lahore City ', 'Model Town ', 'Riawand', 'Shalimar'],
    'Layyah': ['Chaubara', 'Karor Lal Esan', 'Layyah'],
    'Lodhran': ['Dunyapur', 'Kahror Pacca', 'Lodhran'],
    'Mandi Bahauddin': ['Malakwal', 'Mandi Bahauddin', 'Phalia'],
    'Mianwali': ['Isa Khel', 'Mianwali', 'Piplan '],
    'Multan': ['Jalalpur Pirwala', 'Multan City', 'Multan Saddar ', 'Shujabad'],
    'Muzaffargarh': ['Alipur', 'Jatoi', 'Kot Addu', 'Muzaffargarh '],
    'Nankana Sahib': ['Nankana Sahib', 'Sangla Hill', 'Shahkot'],
    'Narowal': ['Narowal', 'Shakargarh', 'Zafarwal'],
    'Okara': ['Depalpur', 'Okara', 'Renala Khurd'],
    'Pakpattan': ['Arifwala', 'Pakpattan'],
    'Rahim Yar Khan': ['Khanpur', 'Liaquatpur', 'Rahim Yar Khan', 'Sadiqabad'],
    'Rajanpur': ['De-excluded area of Rajanpur', 'Jampur', 'Rajanpur', 'Rojhan'],
    'Rawalpindi': ['Gujar Khan', 'Kahuta', 'Kallar Sayyedan', 'Kotli Sattian', 'Murree', 'Rawalpindi', 'Taxila'],
    'Sahiwal': ['Chichawatni', 'Sahiwal'],
    'Sargodha': ['Bhalwal', 'Bhera', 'Kot Momin', 'Sahiwal', 'Sargodha ', 'Shahpur', 'Sillanwali'],
    'Sheikhupura': ['Ferozewala', 'Muridke', 'Safdarabad', 'Sharkpur', 'Sheikhupura'],
    'Sialkot': ['Daska', 'Pasrur', 'Sambrial', 'Sialkot'],
    'Toba Tek Singh': ['Gojra', 'Kamalia', 'Pir Mahal', 'Toba Tek Singh'],
    'Vehari': ['Burewala', 'Mailsi', 'Vehari'],
  },
  'Sindh': {
    'Badin': ['Badin Taluka', 'Golarchi (Shaheed Fazal Rahu) Taluka', 'Matli Taluka', 'Talhar Taluka', 'Tando Bago Taluka'],
    'Dadu': ['Dadu Taluka', 'Johi Taluka', 'Khairpur Nathan Shah Taluka', 'Mehar Taluka'],
    'Ghotki': ['Daharki Taluka', 'Ghotki Taluka', 'Khangarh Taluka', 'Mirpur Mathelo Taluka', 'Ubauro Taluka'],
    'Hyderabad': ['Hyderabad City Taluka', 'Hyderabad Taluka', 'Latifabad Taluka', 'Qasimabad Taluka'],
    'Jacobabad': ['Garhi Khairo Taluka', 'Jacobabad Taluka', 'Thul Taluka'],
    'Jamshoro': ['Kotri Taluka', 'Manjhand Taluka', 'Sehwan Taluka', 'Thano Bula Khan Taluka'],
    'Karachi Central': ['Gulberg Sub Division', 'Liaquatabad Sub Division', 'Nazimabad Sub Division', 'New Karachi Sub Division', 'North Nazimabad Sub Division'],
    'Karachi East': ['Faisal Cantonment', 'Ferozabad Sub Division', 'Gulshan-e-Iqbal Sub Division', 'Gulzar-e-Hijri Sub Division', 'Jamshed Quarters Sub Division'],
    'Karachi South': ['Aram Bagh Sub Division', 'Civil Line Sub Division', 'Clifton Cantonment', 'Garden Sub Division', 'Karachi Cantonment', 'Lyari Sub Division', 'Saddar Sub Division'],
    'Karachi West': ['Baldia Sub Division', 'Harbour Sub Division', 'Mango Pir Sub Division', 'Manora Cantonment', 'Mauripur Sub Division', 'Mominabad Sub Division', 'Orangi Sub Division', 'Sindh Industrial Trading State (SITE) Sub Division'],
    'Kashmore': ['Kandhkot Taluka', 'Kashmor Taluka', 'Tangwani Taluka'],
    'Khairpur': ['Faiz Ganj Taluka', 'Gambat Taluka', 'Khairpur Taluka', 'Kingri Taluka', 'Kot Diji Taluka', 'Mirwah Taluka', 'Nara Taluka', 'Sobho Dero Taluka'],
    'Korangi': ['Korangi Sub Division', 'Landhi Sub Division', 'Model Colony Sub Division', 'Shah Faisal Sub Division'],
    'Larkana': ['Bakrani Taluka', 'Dokri Taluka', 'Larkana Taluka', 'Ratodero Taluka'],
    'Malir': ['Airport Sub Division', 'Bin Qasim Sub Division', 'Gadap Sub Division', 'Ibrahim Hyderi Sub Division', 'Korangi Creek Cantonment', 'Malir Cantonment', 'Murad Memon Sub Division', 'Shah Mureed Sub Division'],
    'Matiari': ['Hala Taluka', 'Matiari Taluka', 'Saeedabad Taluka'],
    'Mirpur Khas': ['Digri Taluka', 'Hussain Bux Mari Taluka', 'Jhudo Taluka', 'Kot Ghulam Muhammad Taluka', 'Mirpur Khas Taluka', 'Shujaabad Taluka', 'Sindhri Taluka'],
    'Naushahro Feroze': ['Bhiria Taluka', 'Kandiaro Taluka', 'Mehrabpur Taluka', 'Moro Taluka', 'Naushahro Feroze Taluka'],
    'Qambar Shahdadkot': ['Kambar Ali Khan Taluka', 'Miro Khan Taluka', 'Nasirabad Taluka', 'Qubo Saeed Khan Taluka', 'Shahdadkot Taluka', 'Sujawal Junejo Taluka', 'Warah Taluka'],
    'Sanghar': ['Jam Nawaz Ali Taluka', 'Khipro Taluka', 'Sanghar Taluka', 'Shahdadpur Taluka', 'Sinjhoro Taluka', 'Tando Adam Taluka'],
    'Shaheed Benazir Abad (Nawabshah)': ['Daur Taluka Taluka', 'Kazi Ahmed (Daulatpur) Taluka', 'Nawabshah Taluka', 'Sakrand Taluka'],
    'Shikarpur': ['Garhi Yasin Taluka', 'Khanpur Taluka', 'Lakhi Taluka', 'Shikarpur Taluka'],
    'Sujawal': ['Jati Taluka', 'Kharo Chan Taluka', 'Mirpur Bathoro Taluka', 'Shah Bunder Taluka', 'Sujawal Taluka'],
    'Sukkur': ['New Sukkur Taluka', 'Pano Aqil Taluka', 'Rohri Taluka', 'Salehpat Taluka', 'Sukkur City Taluka'],
    'Tando Allahyar': ['Chamber Taluka', 'Jhando Mari Taluka', 'Tando Allahyar Taluka'],
    'Tando Muhammad Khan': ['Bulri Shah Karim Taluka', 'Tando Ghulam Hyder Taluka', 'Tando Muhammad Khan Taluka'],
    'Tharparkar': ['Chachro Taluka', 'Dahli Taluka', 'Diplo Taluka', 'Islamkot Taluka', 'Kaloi Taluka', 'Mithi Taluka', 'Nagar Parker Taluka'],
    'Thatta': ['Ghorabari Taluka', 'Keti Bunder Taluka', 'Mirpur Sakro Taluka', 'Thatta Taluka'],
    'Umerkot': ['Kunri Taluka', 'Pithoro Taluka', 'Samaro Taluka', 'Umerkot Taluka'],
  },
}

export function getProvinces(): string[] {
  return Object.keys(PAKISTAN_LOCATIONS)
}

export function getDistricts(province: string): string[] {
  return province ? Object.keys(PAKISTAN_LOCATIONS[province] || {}) : []
}

export function getTehsils(province: string, district: string): string[] {
  return province && district ? PAKISTAN_LOCATIONS[province]?.[district] || [] : []
}